[package]
name = "tfb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansiterm = "0.12.2"
anyhow = "1.0.75"
